CC		= gcc
FLAGS	= -Wall -Wextra -Wpedantic

run-task-1:    #compile and run task1
	gcc task1.c  -o task1 ${FLAGS} && ./task1

run-task-2:    #compile and run task2
	gcc task2.c  -o task2 -lm ${FLAGS} && ./task2

run-task-3:    #compile and run task3
	gcc task3.c  -o task3 -lm ${FLAGS} && ./task3
			